# Generated by Django 3.1.6 on 2021-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=25)),
                ('Prénom', models.CharField(max_length=35)),
                ('Profession', models.CharField(max_length=40)),
                ('Date_de_naissance', models.DateField(max_length=8)),
                ('Sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=200, null=True)),
                ('Nationalité', models.CharField(max_length=40)),
                ('Adresse_physique', models.CharField(max_length=40)),
                ('Téléphone', models.IntegerField()),
                ('Email', models.EmailField(max_length=40)),
                ('Superficie_demandée', models.IntegerField()),
                ('Type_occupation', models.CharField(max_length=40)),
                ('photo', models.ImageField(null=True, upload_to='media/photos')),
                ('date_demande', models.DateTimeField(auto_now_add=True, null=True)),
                ('statut', models.CharField(choices=[('approuvée', 'approuvée'), ('refusée', 'refusée'), ('en attente', 'en attente')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeursMoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_structure', models.CharField(max_length=25)),
                ('date_de_creation', models.DateField()),
                ('Nombre_adhérent', models.IntegerField()),
                ('Adresse_physique', models.CharField(max_length=40)),
                ('Téléphone', models.IntegerField()),
                ('Email', models.EmailField(max_length=40)),
                ('Superficie_demandée', models.IntegerField()),
                ('Type_occupation', models.CharField(max_length=40)),
                ('date_demande', models.DateTimeField(auto_now_add=True, null=True)),
                ('statut', models.CharField(choices=[('approuvée', 'approuvée'), ('refusée', 'refusée'), ('en attente', 'en attente')], max_length=200, null=True)),
            ],
        ),
    ]
