# Generated by Django 3.2.7 on 2021-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeurs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demandeursmoral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
