# Generated by Django 3.1.6 on 2021-12-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonc_app', '0002_auto_20210928_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeurs',
            options={'ordering': ['-date_demande']},
        ),
        migrations.AlterModelOptions(
            name='demandeursmoral',
            options={'ordering': ['-date_demande']},
        ),
        migrations.RenameField(
            model_name='demandeurs',
            old_name='statut',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='demandeursmoral',
            old_name='statut',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='demandeurs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demandeursmoral',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
