# Generated by Django 3.1.6 on 2021-12-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonc_app', '0003_auto_20211223_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeurs',
            old_name='status',
            new_name='statut',
        ),
        migrations.RenameField(
            model_name='demandeursmoral',
            old_name='status',
            new_name='statut',
        ),
    ]
